/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#154212',
        'primary-container': '#2d5a27',
        'primary-fixed': '#bcf0ae',
        'primary-fixed-dim': '#a1d494',
        'on-primary': '#ffffff',
        'on-primary-container': '#9dd090',
        'on-primary-fixed': '#002201',
        'on-primary-fixed-variant': '#23501e',
        'inverse-primary': '#a1d494',
        secondary: '#7c5800',
        'secondary-container': '#feb700',
        'secondary-fixed': '#ffdea8',
        'secondary-fixed-dim': '#ffba20',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6b4b00',
        'on-secondary-fixed': '#271900',
        'on-secondary-fixed-variant': '#5e4200',
        tertiary: '#692000',
        'tertiary-container': '#8b340e',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ffb59a',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffaf92',
        'on-tertiary-fixed': '#380d00',
        'on-tertiary-fixed-variant': '#7f2b05',
        surface: '#f8faf8',
        'surface-dim': '#d8dad9',
        'surface-bright': '#f8faf8',
        'surface-tint': '#3b6934',
        'surface-variant': '#e1e3e1',
        'surface-container': '#eceeec',
        'surface-container-low': '#f2f4f2',
        'surface-container-high': '#e6e9e7',
        'surface-container-highest': '#e1e3e1',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#eff1ef',
        background: '#f8faf8',
        'on-background': '#191c1b',
        'on-surface': '#191c1b',
        'on-surface-variant': '#42493e',
        outline: '#72796e',
        'outline-variant': '#c2c9bb',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        turmeric: '#DAA520',
        saffron: '#feb700',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
      animation: {
        blob: 'blob 7s infinite',
      },
      keyframes: {
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
