/**
 * Food → Wikipedia article title map.
 * When a food item name (after stripping parentheticals) doesn't match
 * the Wikipedia article title exactly, list the override here.
 * Wikipedia REST API: https://en.wikipedia.org/api/rest_v1/page/summary/{title}
 */
export const WIKI_OVERRIDES = {
  // ── Disambiguation (dish) ────────────────────────────────────────────────
  'Sambar':                   'Sambar (dish)',
  'Pongal':                   'Pongal (dish)',
  'Rasam':                    'Rasam',
  'Kootu':                    'Kootu',
  'Vada':                     'Vada (food)',
  'Medu Vada':                'Medu vada',
  'Upma':                     'Upma',
  'Puri':                     'Puri (food)',
  'Halwa':                    'Halwa',
  'Kheer':                    'Kheer',
  'Barfi':                    'Barfi (confectionery)',
  'Ladoo':                    'Laddu',
  'Peda':                     'Peda (confectionery)',
  'Kalakand':                 'Kalakand',
  'Rasgulla':                 'Rasgulla',
  'Jalebi':                   'Jalebi',
  'Payasam':                  'Kheer',
  'Khichdi':                  'Khichdi',
  'Dal':                      'Dal',
  'Pulao':                    'Pilaf',
  'Biryani':                  'Biryani',
  'Roti':                     'Roti',
  'Naan':                     'Naan',
  'Paratha':                  'Paratha',
  'Bhatura':                  'Bhatura',
  'Kulcha':                   'Kulcha',
  'Appam':                    'Appam',
  'Puttu':                    'Puttu',
  'Paneer':                   'Paneer',
  'Ghee':                     'Ghee',
  'Lassi':                    'Lassi',
  'Chai':                     'Masala chai',
  'Thandai':                  'Thandai',
  'Kanji':                    'Kanji (dish)',

  // ── Dishes ───────────────────────────────────────────────────────────────
  'Idli':                     'Idli',
  'Dosa':                     'Dosa',
  'Plain Dosa':               'Dosa',
  'Masala Dosa':              'Masala dosa',
  'Rava Dosa':                'Rava dosa',
  'Uttapam':                  'Uttapam',
  'Pesarattu':                'Pesarattu',
  'Adai':                     'Adai (food)',
  'Idiyappam':                'Idiyappam',
  'Avial':                    'Avial',
  'Bisibele Bath':            'Bisi bele bath',
  'Curd Rice':                'Curd rice',
  'Lemon Rice':               'Lemon rice',
  'Tamarind Rice':            'Puliyodharai',
  'Coconut Rice':             'Coconut rice',
  'Pongal':                   'Pongal (dish)',
  'Ven Pongal':               'Pongal (dish)',
  'Sabudana Khichdi':         'Sabudana khichdi',
  'Poha':                     'Poha',
  'Ven Pongal':               'Pongal (dish)',
  'Thoran':                   'Thoran',
  'Olan':                     'Olan',
  'Erissery':                 'Erissery',
  'Aviyal':                   'Avial',
  'Dal Tadka':                'Dal fry',
  'Dal Makhani':              'Dal makhani',
  'Dal Palak':                'Dal fry',
  'Dal Fry':                  'Dal fry',
  'Rajma':                    'Rajma',
  'Chole':                    'Chole bhature',
  'Chana Masala':             'Chana masala',
  'Palak Paneer':             'Palak paneer',
  'Matar Paneer':             'Mutter paneer',
  'Paneer Butter Masala':     'Paneer makhani',
  'Kadhai Paneer':            'Kadhai paneer',
  'Shahi Paneer':             'Shahi paneer',
  'Aloo Gobhi':               'Aloo gobi',
  'Aloo Matar':               'Aloo matar',
  'Baingan Bharta':           'Baingan bharta',
  'Bhindi Masala':            'Bhindi masala',
  'Sarson da Saag':           'Sarson da saag',
  'Dum Aloo':                 'Dum aloo',
  'Kadhi Pakora':             'Kadhi',
  'Dal Baati Churma':         'Dal baati churma',
  'Malai Kofta':              'Malai kofta',
  'Butter Chicken':           'Butter chicken',
  'Chicken Curry':            'Chicken curry',
  'Chicken Tikka Masala':     'Chicken tikka masala',
  'Chicken Tikka':            'Chicken tikka',
  'Chicken Korma':            'Chicken korma',
  'Tandoori Chicken':         'Tandoori chicken',
  'Mutton Rogan Josh':        'Rogan josh',
  'Rogan Josh':               'Rogan josh',
  'Mutton Curry':             'Mutton curry',
  'Mutton Biryani':           'Biryani',
  'Chicken Biryani':          'Biryani',
  'Vegetable Biryani':        'Biryani',
  'Seekh Kebab':              'Seekh kebab',
  'Shammi Kebab':             'Shami kebab',
  'Galawti Kebab':            'Galouti kebab',
  'Hyderabadi Dum Biryani':   'Hyderabadi biryani',
  'Lucknowi Dum Biryani':     'Awadhi cuisine',
  'Nihari':                   'Nihari',
  'Haleem':                   'Haleem',
  'Keema Matar':              'Keema matar',
  'Egg Curry':                'Egg curry',
  'Fish Curry':               'Fish curry',
  'Samosa':                   'Samosa',
  'Pakora':                   'Pakora',
  'Kachori':                  'Kachori',
  'Vada Pav':                 'Vada pav',
  'Pav Bhaji':                'Pav bhaji',
  'Pani Puri':                'Pani puri',
  'Bhel Puri':                'Bhel puri',
  'Sev Puri':                 'Sev puri',
  'Dahi Vada':                'Dahi vada',
  'Chole Bhature':            'Chole bhature',
  'Dhokla':                   'Dhokla',
  'Khandvi':                  'Khandvi',
  'Undhiyu':                  'Undhiyu',
  'Dal Dhokli':               'Dal dhokli',
  'Shrikhand':                'Shrikhand',
  'Misal Pav':                'Misal pav',
  'Puran Poli':               'Puran poli',
  'Litti Chokha':             'Litti chokha',
  'Pork Vindaloo':            'Vindaloo',
  'Goa Fish Curry':           'Goan fish curry',
  'Bebinca':                  'Bebinca',
  'Momos':                    'Momo (food)',
  'Veg Momos':                'Momo (food)',
  'Chicken Momos':            'Momo (food)',
  'Thukpa':                   'Thukpa',
  'Gulab Jamun':              'Gulab jamun',
  'Rasmalai':                 'Rasmalai',
  'Mysore Pak':               'Mysore pak',
  'Imarti':                   'Imarti',
  'Ghevar':                   'Ghevar',
  'Phirni':                   'Phirni',
  'Churma':                   'Churma',
  'Mishti Doi':               'Mishti doi',
  'Sandesh':                  'Sandesh (confectionery)',
  'Kaalan':                   'Kaalan (dish)',
  'Chettinad Chicken Curry':  'Chettinad cuisine',
  'Chicken 65':               'Chicken 65',
  'Kothu Parotta':            'Kothu parotta',
  'Parotta':                  'Parotta',
  'Meen Kuzhambu':            'Meen kulambu',
  'Kolhapuri Chicken':        'Kolhapuri cuisine',
  'Rogan Josh':               'Rogan josh',
  'Kehwa':                    'Kahwa',
  'Aloo Posto':               'Aloo posto',
  'Shukto':                   'Shukto',
  'Kosha Mangsho':            'Kosha mangsho',
  'Luchi':                    'Luchi',
  'Ilish Bhapa':              'Ilish',
  'Hilsa Fish':               'Ilish',
  'Dalma':                    'Dalma (food)',
  'Chhena Poda':              'Chhena poda',
  'Masor Tenga':              'Masor tenga',
  'Laal Maas':                'Laal maas',

  // ── Breads ───────────────────────────────────────────────────────────────
  'Chapati':                  'Chapati',
  'Phulka':                   'Chapati',
  'Makki di Roti':            'Makki di roti',
  'Bajra Roti':               'Bajra',
  'Rumali Roti':              'Rumali roti',
  'Sheermal':                 'Sheermal',
  'Bhatura':                  'Bhatura',

  // ── Fruits ───────────────────────────────────────────────────────────────
  'Mango':                    'Mango',
  'Alphonso Mango':           'Alphonso mango',
  'Kesar Mango':              'Mango',
  'Dashehari Mango':          'Mango',
  'Langra Mango':             'Mango',
  'Raw Mango':                'Mango',
  'Banana':                   'Banana',
  'Robusta Banana':           'Banana',
  'Nendran Banana':           'Nendran banana',
  'Raw Banana':               'Cooking banana',
  'Banana Flower':            'Banana flower',
  'Apple':                    'Apple',
  'Orange':                   'Orange (fruit)',
  'Papaya':                   'Papaya',
  'Raw Papaya':               'Papaya',
  'Pineapple':                'Pineapple',
  'Watermelon':               'Watermelon',
  'Muskmelon':                'Muskmelon',
  'Jackfruit':                'Jackfruit',
  'Guava':                    'Guava',
  'Pomegranate':              'Pomegranate',
  'Coconut':                  'Coconut',
  'Tender Coconut':           'Coconut',
  'Lemon':                    'Lemon',
  'Lime':                     'Key lime',
  'Amla':                     'Indian gooseberry',
  'Indian Gooseberry':        'Indian gooseberry',
  'Litchi':                   'Lychee',
  'Lychee':                   'Lychee',
  'Chikoo':                   'Sapodilla',
  'Sapota':                   'Sapodilla',
  'Custard Apple':            'Custard apple',
  'Sitaphal':                 'Custard apple',
  'Dragon Fruit':             'Dragon fruit',
  'Kiwi':                     'Kiwifruit',
  'Strawberry':               'Strawberry',
  'Grapes':                   'Grape',
  'Black Grapes':             'Grape',
  'Green Grapes':             'Grape',
  'Blueberry':                'Blueberry',
  'Raspberry':                'Raspberry',
  'Avocado':                  'Avocado',
  'Plum':                     'Plum',
  'Peach':                    'Peach',
  'Apricot':                  'Apricot',
  'Pear':                     'Pear',
  'Dates':                    'Date (fruit)',
  'Fig':                      'Common fig',
  'Raisins':                  'Raisin',
  'Dried Mango':              'Mango',
  'Tamarind':                 'Tamarind',
  'Kokum':                    'Kokum',
  'Wood Apple':               'Wood apple',
  'Star Fruit':               'Carambola',
  'Mulberry':                 'Mulberry',
  'Jamun':                    'Java plum',
  'Karonda':                  'Natal plum',
  'Phalsa':                   'Grewia asiatica',
  'Bael':                     'Bael',

  // ── Vegetables ───────────────────────────────────────────────────────────
  'Tomato':                   'Tomato',
  'Onion':                    'Onion',
  'Garlic':                   'Garlic',
  'Ginger':                   'Ginger',
  'Potato':                   'Potato',
  'Sweet Potato':             'Sweet potato',
  'Carrot':                   'Carrot',
  'Beetroot':                 'Beetroot',
  'Radish':                   'Radish',
  'Turnip':                   'Turnip',
  'Cauliflower':              'Cauliflower',
  'Cabbage':                  'Cabbage',
  'Broccoli':                 'Broccoli',
  'Spinach':                  'Spinach',
  'Fenugreek Leaves':         'Fenugreek',
  'Methi Leaves':             'Fenugreek',
  'Moringa Leaves':           'Moringa oleifera',
  'Drumstick':                'Moringa oleifera',
  'Curry Leaves':             'Curry tree',
  'Coriander Leaves':         'Coriander',
  'Mint Leaves':              'Mentha',
  'Brinjal':                  'Eggplant',
  'Eggplant':                 'Eggplant',
  'Okra':                     'Okra',
  'Ladies Finger':            'Okra',
  'Bitter Gourd':             'Bitter melon',
  'Bottle Gourd':             'Calabash',
  'Ridge Gourd':              'Ridged gourd',
  'Snake Gourd':              'Snake gourd',
  'Ash Gourd':                'Winter melon',
  'Pumpkin':                  'Pumpkin',
  'Zucchini':                 'Zucchini',
  'Capsicum':                 'Bell pepper',
  'Green Chilli':             'Chili pepper',
  'Mushroom':                 'Mushroom',
  'Button Mushroom':          'Agaricus bisporus',
  'Yam':                      'Yam',
  'Taro Root':                'Taro',
  'Colocasia':                'Taro',
  'Lotus Stem':               'Nelumbo nucifera',
  'Banana Stem':              'Cooking banana',
  'Raw Jackfruit':            'Jackfruit',
  'Corn':                     'Maize',
  'Peas':                     'Pea',

  // ── Grains & Millets ─────────────────────────────────────────────────────
  'Ragi':                     'Finger millet',
  'Finger Millet':            'Finger millet',
  'Bajra':                    'Pearl millet',
  'Pearl Millet':             'Pearl millet',
  'Jowar':                    'Sorghum',
  'Sorghum':                  'Sorghum',
  'Foxtail Millet':           'Foxtail millet',
  'Kodo Millet':              'Paspalum scrobiculatum',
  'Barnyard Millet':          'Barnyard millet',
  'Little Millet':            'Panicum sumatrense',
  'Brown Top Millet':         'Brachiaria ramosa',
  'Amaranth':                 'Amaranth grain',
  'Quinoa':                   'Quinoa',
  'Buckwheat':                'Buckwheat',
  'White Rice':               'White rice',
  'Brown Rice':               'Brown rice',
  'Basmati Rice':             'Basmati',
  'Parboiled Rice':           'Parboiled rice',
  'Black Rice':               'Black rice',
  'Red Rice':                 'Red rice',
  'Poha':                     'Poha',
  'Murmura':                  'Puffed rice',
  'Puffed Rice':              'Puffed rice',
  'Whole Wheat Flour':        'Whole wheat flour',
  'Semolina':                 'Semolina',
  'Oats':                     'Oat',
  'Barley':                   'Barley',
  'Maize':                    'Maize',
  'Sabudana':                 'Tapioca',
  'Makhana':                  'Euryale ferox',
  'Fox Nuts':                 'Euryale ferox',

  // ── Legumes ──────────────────────────────────────────────────────────────
  'Moong Dal':                'Mung bean',
  'Masoor Dal':               'Lentil',
  'Toor Dal':                 'Pigeon pea',
  'Urad Dal':                 'Urad bean',
  'Chana Dal':                'Chickpea',
  'Kabuli Chana':             'Chickpea',
  'Kala Chana':               'Chickpea',
  'Rajma':                    'Kidney bean',
  'Peanuts':                  'Peanut',
  'Groundnuts':               'Peanut',
  'Soybean':                  'Soybean',
  'Tofu':                     'Tofu',
  'Tempe':                    'Tempeh',
  'Cowpea':                   'Cowpea',
  'Horse Gram':               'Horse gram',
  'Moth Bean':                'Moth bean',

  // ── Nuts & Seeds ─────────────────────────────────────────────────────────
  'Almonds':                  'Almond',
  'Cashews':                  'Cashew',
  'Walnuts':                  'Walnut',
  'Pistachios':               'Pistachio',
  'Hazelnuts':                'Hazel',
  'Brazil Nuts':              'Brazil nut',
  'Pine Nuts':                'Pine nut',
  'Macadamia Nuts':           'Macadamia',
  'Desiccated Coconut':       'Coconut',
  'White Sesame Seeds':       'Sesame',
  'Black Sesame Seeds':       'Sesame',
  'Flaxseeds':                'Flax',
  'Sunflower Seeds':          'Sunflower seed',
  'Pumpkin Seeds':            'Pumpkin seed',
  'Chia Seeds':               'Chia seed',
  'Hemp Seeds':               'Hemp',
  'Poppy Seeds':              'Poppy seed',

  // ── Spices ───────────────────────────────────────────────────────────────
  'Turmeric':                 'Turmeric',
  'Cumin':                    'Cumin',
  'Coriander Seeds':          'Coriander',
  'Cardamom':                 'Cardamom',
  'Cloves':                   'Clove',
  'Cinnamon':                 'Cinnamon',
  'Black Pepper':             'Black pepper',
  'Star Anise':               'Illicium verum',
  'Fenugreek Seeds':          'Fenugreek',
  'Mustard Seeds':            'Mustard seed',
  'Saffron':                  'Saffron',
  'Asafoetida':               'Asafoetida',
  'Bay Leaves':               'Bay leaf',
  'Nutmeg':                   'Nutmeg',
  'Mace':                     'Nutmeg',
  'Garam Masala':             'Garam masala',
  'Chaat Masala':             'Chaat masala',
  'Sambar Powder':            'Sambar (dish)',
  'Red Chilli Powder':        'Chili pepper',
  'Vanilla':                  'Vanilla',
  'Ashwagandha':              'Withania somnifera',
  'Moringa Powder':           'Moringa oleifera',

  // ── Dairy ────────────────────────────────────────────────────────────────
  'Whole Cow Milk':           'Milk',
  'Buffalo Milk':             'Buffalo milk',
  'Curd':                     'Dahi (food)',
  'Greek Yogurt':             'Strained yogurt',
  'Paneer':                   'Paneer',
  'Butter':                   'Butter',
  'Ghee':                     'Ghee',
  'Condensed Milk':           'Condensed milk',
  'Khoa':                     'Khoa',

  // ── Meat & Seafood ───────────────────────────────────────────────────────
  'Whole Egg':                'Egg',
  'Boiled Egg':               'Boiled egg',
  'Chicken Breast':           'Chicken as food',
  'Mutton':                   'Lamb and mutton',
  'Mutton Curry':             'Mutton curry',
  'Rohu Fish':                'Rohu',
  'Pomfret':                  'Pomfret',
  'Sardines':                 'Sardine',
  'Tuna Fish':                'Tuna',
  'Salmon Fish':              'Salmon',
  'Prawns':                   'Shrimp',
  'Crab':                     'Crab',

  // ── Oils ─────────────────────────────────────────────────────────────────
  'Coconut Oil':              'Coconut oil',
  'Mustard Oil':              'Mustard oil',
  'Sesame Oil':               'Sesame oil',
  'Groundnut Oil':            'Peanut oil',
  'Sunflower Oil':            'Sunflower oil',
  'Olive Oil':                'Olive oil',
  'Rice Bran Oil':            'Rice bran oil',
  'Ghee':                     'Ghee',

  // ── Beverages ────────────────────────────────────────────────────────────
  'Masala Chai':              'Masala chai',
  'Green Tea':                'Green tea',
  'Black Tea':                'Black tea',
  'Filter Coffee':            'Indian filter coffee',
  'Sweet Lassi':              'Lassi',
  'Plain Lassi':              'Lassi',
  'Mango Lassi':              'Lassi',
  'Chaas':                    'Buttermilk',
  'Sugarcane Juice':          'Sugarcane juice',
  'Tender Coconut Water':     'Coconut water',
  'Turmeric Milk':            'Golden milk',
  'Aam Panna':                'Aam panna',
  'Jaljeera':                 'Jal-jeera',
  'Thandai':                  'Thandai',
  'Badam Milk':               'Badam milk',
}

/**
 * Given a food item, returns the best Wikipedia article title to look up.
 * Returns null if no reasonable title can be determined.
 */
export function getWikiTitle(item) {
  if (!item) return null

  // Strip parenthetical notes: "Idli (Steamed Rice Cake)" → "Idli"
  const cleanName = item.name.replace(/\s*\([^)]*\)/g, '').trim()

  // 1. Direct override by clean name
  if (WIKI_OVERRIDES[cleanName]) return WIKI_OVERRIDES[cleanName]

  // 2. Direct override by original name
  if (WIKI_OVERRIDES[item.name]) return WIKI_OVERRIDES[item.name]

  // 3. Use the cleaned name as-is (works for most English food names)
  if (cleanName.length > 1) return cleanName

  return null
}

/**
 * Category-level gradient colors for the emoji fallback card.
 * Used when no image is available.
 */
export const CATEGORY_GRADIENTS = {
  fruit:     'from-orange-100 to-amber-50',
  vegetable: 'from-green-100 to-emerald-50',
  grain:     'from-yellow-100 to-amber-50',
  millet:    'from-lime-100 to-green-50',
  legume:    'from-amber-100 to-yellow-50',
  nut_seed:  'from-amber-200 to-orange-50',
  spice:     'from-red-100 to-orange-50',
  herb:      'from-emerald-100 to-green-50',
  dairy:     'from-blue-50 to-sky-50',
  dish:      'from-orange-100 to-red-50',
  sweet:     'from-pink-100 to-rose-50',
  snack:     'from-yellow-100 to-orange-50',
  beverage:  'from-cyan-100 to-blue-50',
  meat:      'from-red-100 to-orange-50',
  seafood:   'from-blue-100 to-cyan-50',
  egg:       'from-yellow-100 to-amber-50',
  oil:       'from-amber-100 to-yellow-50',
  bread:     'from-amber-100 to-orange-50',
  fermented: 'from-lime-100 to-yellow-50',
  condiment: 'from-red-100 to-orange-50',
}
